### ISSUE TITLE
ImportProjectFromFile decode error

### ISSUE THREAD

**Issue by DavidPMika** [hutcheb/acd#15]
from acd.api import ImportProjectFromFile
controller = ImportProjectFromFile("my.ACD").import_project().controller

results in

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/m/.local/lib/python3.10/site-packages/acd/api.py", line 44, in import_project
    export = ExportL5x(self.filename)
  File "<string>", line 7, in __init__
  File "/home/m/.local/lib/python3.10/site-packages/acd/l5x/export_l5x.py", line 114, in __post_init__
    CommentsRecord(self._cur, record)
  File "<string>", line 5, in __init__
  File "/home/m/.local/lib/python3.10/site-packages/acd/record/comments.py", line 16, in __post_init__
    r = FafaComents.from_bytes(self.dat_record.record.record_buffer)
  File "/home/m/.local/lib/python3.10/site-packages/kaitaistruct.py", line 52, in from_bytes
    return cls(KaitaiStream(BytesIO(buf)))
  File "/home/m/.local/lib/python3.10/site-packages/acd/generated/comments/fafa_coments.py", line 19, in __init__
    self._read()
  File "/home/m/.local/lib/python3.10/site-packages/acd/generated/comments/fafa_coments.py", line 38, in _read
    self.body = FafaComents.AsciiRecord(_io__raw_body, self, self._root)
  File "/home/m/.local/lib/python3.10/site-packages/acd/generated/comments/fafa_coments.py", line 84, in __init__
    self._read()
  File "/home/m/.local/lib/python3.10/site-packages/acd/generated/comments/fafa_coments.py", line 92, in _read
    self._io.read_bytes_term(0, False, True, True)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9e in position 0: invalid start byte

**Comment by dwbeattie1** [comment]
Following up on decode failures during `ImportProjectFromFile` (related to #14 / this thread).

We hit this on a **large production Rockwell `.ACD`** (Controller-family export, not sharing the file here). With stock `hutcheb/acd` and **no** local patches:

```python
from acd.api import ImportProjectFromFile
ImportProjectFromFile("…/production.acd").import_project()
```

**Observed** during Comps load, before controller build completes:

```
UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 4-5: illegal UTF-16 surrogate
```

Stack points at generated comps **`StrzUtf16._read`** (UTF-16LE `record_name` / similar string fields). The on-disk bytes appear to include **invalid surrogate pairs**, which strict UTF-16 decoding rejects.

**Note:** merged PR #18 already used `errors="replace"` on some UTF-8 comment paths; the comps UTF-16 path still looks strict. A minimal parallel change in `StrzUtf16._read` would be along the lines of:

```python
self.value = raw.decode("utf-16le", errors="replace")
```

(terminator validation unchanged). We are not proposing a PR from our side yet—reporting the symptom and location only.

Happy to re-test on a maintainer branch if you add a guard; we can validate against the same class of production ACD offline.
